#!/data/data/com.termux/files/usr/bin/sh
da=$( echo $1 )
if [  "$da" = "chsh" ]; then 
	echo "using fixedshell as default shell\n this will redirect to current default shell"
	chsh
	mv ~/.termux/shell ~/.fixedshell
	ln -sf $( which fixedshell ) ~/.termux/shell
	exit
fi
if [ -f ~/.termux/shell ]; then
	shell=$(basename $(readlink ~/.termux/shell))
	if [ $shell = "fixedshell" ]; then
		if [ -f ~/.fixedshell ]; then
			shell=$(basename $(readlink ~/.fixedshell))
		else 
			shell=bash
		fi
	fi
else
	shell=bash
fi
if [ "$da" = "" ]; then
	echo "starting $shell with working shebangs"
	LD_PRELOAD=$PREFIX/lib/libandroid-fixshebang.so exec $shell

elif [ "$da" = "-l" ]; then
	echo "starting $shell with working shebangs"
	LD_PRELOAD=$PREFIX/lib/libandroid-fixshebang.so exec $shell  $1 $2 $3
else
	echo "starting $@ with working shebangs"
	LD_PRELOAD=$PREFIX/lib/libandroid-fixshebang.so exec $@
fi
